name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno-version: [v1.x]
        os: [ubuntu-22.04, macos-12, windows-2022]

    env:
      DENO_DIR: '%LOCALAPPDATA%/deno'

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Unit test
        run: deno test test/unit
